# Definindo o nome do Workflow

name: Teste Workflow

# Definindo quando o Workflow será disparado
on:
  # Aciona o fluxo de trabalho em eventos de solicitação push ou pull, mas apenas para o branch "main"
  push:
    branches: [ "main" , "developer"]

  # Permite que você execute este fluxo de trabalho manualmente na guia Ações
  # workflow_dispatch:

# Definindo os jobs que o workflow executará
jobs:
  test_job:
    name: Executando job de teste
    # O tipo de runner em que o job será executado
    runs-on: ubuntu-latest

    # Os Steps representam uma sequência de tarefas que serão executadas como parte do job
    steps:
    - name: Checkout code
      # Faz check-out do seu repositório em $GITHUB_WORKSPACE, para que seu job possa acessá-lo
      uses: actions/checkout@v3

    - name: Docker Login       
      uses: docker/login-action@v3.0.0
      with:
        # Username used to log against the Docker registry
        username: 'rockie88'
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_HUB_PSW }}      

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:      
        context: .
        tags: latest
        push: true
         
   
